env:
  node: true
  browser: true
  es2021: true
extends:
  - plugin:vue/recommended
  - eslint:recommended
globals:
  gapi: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules:
  indent:
    - 'error'
    - 4
    - SwitchCase: 1
  vue/html-indent: ['error', 4]
