version: '3'
services:

  backend:
    command: node ./src/index.js
    dns:
      - 8.8.8.8
    image: node:14.15.4-alpine3.12
    restart: always
    volumes:
      - ./packages/backend:/app
    working_dir: /app

  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./packages/frontend/build:/app

  mongodb:
    environment:
      MONGO_INITDB_DATABASE: app
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017
    image: mongo:4.4.2-bionic
    restart: always
