version: '3'
services:

  backend:
    command: node ./src/index.js
    image: node:14.15.4-alpine3.12
    volumes:
      - ./packages/backend:/app
    working_dir: /app

  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - 8000:8000
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./packages/frontend/build:/app
